# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(703, 602)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 191, 151))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.login_form = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.login_form.setContentsMargins(0, 0, 0, 0)
        self.login_form.setObjectName("login_form")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.line_user = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.line_user.setObjectName("line_user")
        self.horizontalLayout_4.addWidget(self.line_user)
        self.login_form.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.line_pwd = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.line_pwd.setObjectName("line_pwd")
        self.horizontalLayout_3.addWidget(self.line_pwd)
        self.login_form.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.line_host = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.line_host.setObjectName("line_host")
        self.horizontalLayout_2.addWidget(self.line_host)
        self.login_form.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.line_db = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.line_db.setObjectName("line_db")
        self.horizontalLayout.addWidget(self.line_db)
        self.login_form.addLayout(self.horizontalLayout)
        self.connect_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.connect_button.setObjectName("connect_button")
        self.login_form.addWidget(self.connect_button)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(220, 10, 471, 411))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.query_form = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.query_form.setContentsMargins(0, 0, 0, 0)
        self.query_form.setObjectName("query_form")
        self.tableWidget = QtWidgets.QTableWidget(self.verticalLayoutWidget_2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.query_form.addWidget(self.tableWidget)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.comboBox_tables = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.comboBox_tables.setObjectName("comboBox_tables")
        self.horizontalLayout_5.addWidget(self.comboBox_tables)
        self.query_form.addLayout(self.horizontalLayout_5)
        self.button_tables = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.button_tables.setObjectName("button_tables")
        self.query_form.addWidget(self.button_tables)
        self.comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.comboBox.setObjectName("comboBox")
        self.query_form.addWidget(self.comboBox)
        self.render_button = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.render_button.setObjectName("render_button")
        self.query_form.addWidget(self.render_button)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 703, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "user"))
        self.line_user.setText(_translate("MainWindow", "postgres"))
        self.label_3.setText(_translate("MainWindow", "pass"))
        self.line_pwd.setText(_translate("MainWindow", "1"))
        self.label_2.setText(_translate("MainWindow", "host"))
        self.line_host.setText(_translate("MainWindow", "localhost"))
        self.label.setText(_translate("MainWindow", "db"))
        self.line_db.setText(_translate("MainWindow", "postgres"))
        self.connect_button.setText(_translate("MainWindow", "login"))
        self.button_tables.setText(_translate("MainWindow", "показать таблицу"))
        self.render_button.setText(_translate("MainWindow", "показать запрос"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

